version: '3.3'

volumes:
  postgres_data:
      driver: local

services:
  nginx: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www
      - ./certs/:/etc/certs/      
    ports:
      - 80:80
      - 443:443
  
  postgres:
      image: postgres
      container_name: postgres
      restart: unless-stopped
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
  
  mykeycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      restart: unless-stopped
      command: ["-Djboss.socket.binding.port-offset=100"]
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
        KEYCLOAK_USER: qwokka
        KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        PROXY_ADDRESS_FORWARDING: "true"
        JDBC_PARAMS: enabledTLSProtocols=TLSv1.2
        JDBC_PARAMS: useSSL=false
        JAVA_OPTS: -server -Xms1024m -Xmx1024m
      ports:
        - 8180:8080
      depends_on:
        postgres:
          condition: service_healthy
      healthcheck:
        test: "curl -f https://mykeycloak/auth || exit 1"
        start_period: 30s
  
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
