version: '3.3'

services:
  nginx_rproxy: 
    image: nginx:latest
    container_name: nginx_rproxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/data/www  
    ports:
      - 80:80
  mykeycloak:
    image: jboss/keycloak:latest
    container_name: mykeycloak
    restart: unless-stopped    
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true  #important for reverse proxy    
